// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: demo_hxd8357d

#include "../ui.h"

void ui_main_screen_init(void)
{
  ui_main = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_main, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_bg_color(ui_main,
                            lv_color_hex(0xFFFFFF),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Image19 = lv_img_create(ui_main);
  lv_img_set_src(ui_Image19, &ui_img_842152610);
  lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT); /// 300
  lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);  /// 148
  lv_obj_set_x(ui_Image19, -197);
  lv_obj_set_y(ui_Image19, -132);
  lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_Image19, 50);

  ui_led0panel = lv_obj_create(ui_main);
  lv_obj_set_width(ui_led0panel, 165);
  lv_obj_set_height(ui_led0panel, 105);
  lv_obj_set_x(ui_led0panel, -143);
  lv_obj_set_y(ui_led0panel, -31);
  lv_obj_set_align(ui_led0panel, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_led0panel, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_bg_color(ui_led0panel,
                            lv_color_hex(0xFFFFFF),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_led0panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_led0panel,
                                lv_color_hex(0x7D7D7D),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_led0panel, 255,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_led0panel, 1,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_led0panel,
                               LV_BORDER_SIDE_FULL,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_led0panel,
                                lv_color_hex(0xB6B6B6),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_led0panel, 255,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_width(ui_led0panel, 1,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_spread(ui_led0panel,
                                 0,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_ofs_x(ui_led0panel, 1,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_ofs_y(ui_led0panel, 1,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_led0OffSymbol = lv_img_create(ui_led0panel);
  lv_img_set_src(ui_led0OffSymbol, &ui_img_buld_off_png);
  lv_obj_set_width(ui_led0OffSymbol, LV_SIZE_CONTENT); /// 1
  lv_obj_set_height(ui_led0OffSymbol, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_led0OffSymbol, -56);
  lv_obj_set_y(ui_led0OffSymbol, -24);
  lv_obj_set_align(ui_led0OffSymbol, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_led0OffSymbol, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_led0OffSymbol, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_led0OffSymbol, 50);

  ui_led0ONSymbol = lv_img_create(ui_led0panel);
  lv_img_set_src(ui_led0ONSymbol, &ui_img_buld_on_png);
  lv_obj_set_width(ui_led0ONSymbol, LV_SIZE_CONTENT); /// 1
  lv_obj_set_height(ui_led0ONSymbol, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_led0ONSymbol, -56);
  lv_obj_set_y(ui_led0ONSymbol, -31);
  lv_obj_set_align(ui_led0ONSymbol, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_led0ONSymbol, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_led0ONSymbol, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_led0ONSymbol, 55);

  ui_livingRoomlabel = lv_label_create(ui_led0panel);
  lv_obj_set_width(ui_livingRoomlabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_height(ui_livingRoomlabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_livingRoomlabel, 51);
  lv_obj_set_y(ui_livingRoomlabel, 24);
  lv_obj_set_align(ui_livingRoomlabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_livingRoomlabel, "Living \nRoom");
  lv_obj_set_style_text_color(ui_livingRoomlabel,
                              lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_livingRoomlabel,
                            255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_led0OnLabel = lv_label_create(ui_led0panel);
  lv_obj_set_width(ui_led0OnLabel, LV_SIZE_CONTENT); /// 100
  lv_obj_set_height(ui_led0OnLabel, LV_SIZE_CONTENT);  /// 100
  lv_obj_set_x(ui_led0OnLabel, -2);
  lv_obj_set_y(ui_led0OnLabel, -19);
  lv_obj_set_align(ui_led0OnLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_led0OnLabel, "- ON");
  lv_obj_set_style_text_color(ui_led0OnLabel,
                              lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_led0OnLabel, 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_led0OnLabel,
                             &lv_font_montserrat_14,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_led0OffLabel = lv_label_create(ui_led0panel);
  lv_obj_set_width(ui_led0OffLabel, LV_SIZE_CONTENT); /// 100
  lv_obj_set_height(ui_led0OffLabel, LV_SIZE_CONTENT);  /// 100
  lv_obj_set_x(ui_led0OffLabel, 1);
  lv_obj_set_y(ui_led0OffLabel, -19);
  lv_obj_set_align(ui_led0OffLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_led0OffLabel, "- OFF");
  lv_obj_set_style_text_color(ui_led0OffLabel,
                              lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_led0OffLabel,
                            255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_led0OffLabel,
                             &lv_font_montserrat_14,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_led0Switch = lv_switch_create(ui_led0panel);
  lv_obj_set_width(ui_led0Switch, 50);
  lv_obj_set_height(ui_led0Switch, 20);
  lv_obj_set_x(ui_led0Switch, -46);
  lv_obj_set_y(ui_led0Switch, 33);
  lv_obj_set_align(ui_led0Switch, LV_ALIGN_CENTER);
  lv_obj_set_style_bg_color(ui_led0Switch,
                            lv_color_hex(0x5F8493),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_led0Switch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_led1panel = lv_obj_create(ui_main);
  lv_obj_set_width(ui_led1panel, 165);
  lv_obj_set_height(ui_led1panel, 105);
  lv_obj_set_x(ui_led1panel, -144);
  lv_obj_set_y(ui_led1panel, 89);
  lv_obj_set_align(ui_led1panel, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_led1panel, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_bg_color(ui_led1panel,
                            lv_color_hex(0xFFFFFF),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_led1panel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_led1panel,
                                lv_color_hex(0x7D7D7D),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_led1panel, 255,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_led1panel, 1,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_led1panel,
                               LV_BORDER_SIDE_FULL,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_led1panel,
                                lv_color_hex(0xB6B6B6),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_led1panel, 255,
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_width(ui_led1panel, 1,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_spread(ui_led1panel,
                                 0,
                                 LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_ofs_x(ui_led1panel, 1,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_ofs_y(ui_led1panel, 1,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_led1OffSymbol = lv_img_create(ui_led1panel);
  lv_img_set_src(ui_led1OffSymbol, &ui_img_buld_off_png);
  lv_obj_set_width(ui_led1OffSymbol, LV_SIZE_CONTENT); /// 1
  lv_obj_set_height(ui_led1OffSymbol, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_led1OffSymbol, -56);
  lv_obj_set_y(ui_led1OffSymbol, -24);
  lv_obj_set_align(ui_led1OffSymbol, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_led1OffSymbol, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_led1OffSymbol, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_led1OffSymbol, 50);

  ui_led1ONSymbol = lv_img_create(ui_led1panel);
  lv_img_set_src(ui_led1ONSymbol, &ui_img_buld_on_png);
  lv_obj_set_width(ui_led1ONSymbol, LV_SIZE_CONTENT); /// 1
  lv_obj_set_height(ui_led1ONSymbol, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_led1ONSymbol, -55);
  lv_obj_set_y(ui_led1ONSymbol, -31);
  lv_obj_set_align(ui_led1ONSymbol, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_led1ONSymbol, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_led1ONSymbol, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_led1ONSymbol, 55);

  ui_KitchenRoomlabel = lv_label_create(ui_led1panel);
  lv_obj_set_width(ui_KitchenRoomlabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_height(ui_KitchenRoomlabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_KitchenRoomlabel, 51);
  lv_obj_set_y(ui_KitchenRoomlabel, 24);
  lv_obj_set_align(ui_KitchenRoomlabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_KitchenRoomlabel, "Kitchen \nRoom");
  lv_obj_set_style_text_color(ui_KitchenRoomlabel,
                              lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_KitchenRoomlabel,
                            255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_led1OnLabel = lv_label_create(ui_led1panel);
  lv_obj_set_width(ui_led1OnLabel, LV_SIZE_CONTENT); /// 100
  lv_obj_set_height(ui_led1OnLabel, LV_SIZE_CONTENT);  /// 100
  lv_obj_set_x(ui_led1OnLabel, -4);
  lv_obj_set_y(ui_led1OnLabel, -19);
  lv_obj_set_align(ui_led1OnLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_led1OnLabel, "- ON");
  lv_obj_set_style_text_color(ui_led1OnLabel,
                              lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_led1OnLabel, 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_led1OnLabel,
                             &lv_font_montserrat_14,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_led1OffLabel = lv_label_create(ui_led1panel);
  lv_obj_set_width(ui_led1OffLabel, LV_SIZE_CONTENT); /// 100
  lv_obj_set_height(ui_led1OffLabel, LV_SIZE_CONTENT);  /// 100
  lv_obj_set_x(ui_led1OffLabel, -1);
  lv_obj_set_y(ui_led1OffLabel, -19);
  lv_obj_set_align(ui_led1OffLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_led1OffLabel, "- OFF");
  lv_obj_set_style_text_color(ui_led1OffLabel,
                              lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_led1OffLabel,
                            255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_led1OffLabel,
                             &lv_font_montserrat_14,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_led1Switch = lv_switch_create(ui_led1panel);
  lv_obj_set_width(ui_led1Switch, 50);
  lv_obj_set_height(ui_led1Switch, 20);
  lv_obj_set_x(ui_led1Switch, -46);
  lv_obj_set_y(ui_led1Switch, 33);
  lv_obj_set_align(ui_led1Switch, LV_ALIGN_CENTER);
  lv_obj_set_style_bg_color(ui_led1Switch,
                            lv_color_hex(0x5F8493),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_led1Switch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_Panel7 = lv_obj_create(ui_main);
  lv_obj_set_width(ui_Panel7, 174);
  lv_obj_set_height(ui_Panel7, 231);
  lv_obj_set_x(ui_Panel7, 102);
  lv_obj_set_y(ui_Panel7, 27);
  lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_bg_color(ui_Panel7,
                            lv_color_hex(0xFFFFFF),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_Panel7,
                                lv_color_hex(0xD2D2D2),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_Panel7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_color(ui_Panel7,
                                lv_color_hex(0x8B8B8B),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_width(ui_Panel7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_spread(ui_Panel7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_ofs_x(ui_Panel7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_shadow_ofs_y(ui_Panel7, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_buttonLabel = lv_label_create(ui_Panel7);
  lv_obj_set_width(ui_buttonLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_height(ui_buttonLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_buttonLabel, -45);
  lv_obj_set_y(ui_buttonLabel, -95);
  lv_obj_set_align(ui_buttonLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_buttonLabel, "Button");
  lv_obj_set_style_text_color(ui_buttonLabel,
                              lv_color_hex(0x242424),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_buttonLabel, 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_buttonOffSymbol = lv_img_create(ui_Panel7);
  lv_img_set_src(ui_buttonOffSymbol, &ui_img_button1_off_png);
  lv_obj_set_width(ui_buttonOffSymbol, LV_SIZE_CONTENT); /// 1
  lv_obj_set_height(ui_buttonOffSymbol, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_buttonOffSymbol, 2);
  lv_obj_set_y(ui_buttonOffSymbol, 8);
  lv_obj_set_align(ui_buttonOffSymbol, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_buttonOffSymbol, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_buttonOffSymbol, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_buttonOffSymbol, 80);

  ui_buttonOnSymbol = lv_img_create(ui_Panel7);
  lv_img_set_src(ui_buttonOnSymbol, &ui_img_button1_on_png);
  lv_obj_set_width(ui_buttonOnSymbol, LV_SIZE_CONTENT); /// 1
  lv_obj_set_height(ui_buttonOnSymbol, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_buttonOnSymbol, 2);
  lv_obj_set_y(ui_buttonOnSymbol, 7);
  lv_obj_set_align(ui_buttonOnSymbol, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_buttonOnSymbol, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_buttonOnSymbol, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_img_set_zoom(ui_buttonOnSymbol, 80);

  ui_mainLabel = lv_label_create(ui_main);
  lv_obj_set_width(ui_mainLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_height(ui_mainLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_mainLabel, 30);
  lv_obj_set_y(ui_mainLabel, -129);
  lv_obj_set_align(ui_mainLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_mainLabel, "ADAFRUIT HXD8357D TFT LCD EXAMPLE");
  lv_obj_set_style_text_color(ui_mainLabel,
                              lv_color_hex(0x020362),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_mainLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_add_event_cb(ui_led0Switch, ui_event_led0Switch, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_led1Switch, ui_event_led1Switch, LV_EVENT_ALL, NULL);
}
