// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: demo_hxd8357d

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_main
void ui_main_screen_init(void);

lv_obj_t *ui_main;
lv_obj_t *ui_Image19;
lv_obj_t *ui_led0panel;
lv_obj_t *ui_led0OffSymbol;
lv_obj_t *ui_led0ONSymbol;
lv_obj_t *ui_livingRoomlabel;
lv_obj_t *ui_led0OnLabel;
lv_obj_t *ui_led0OffLabel;
void ui_event_led0Switch(lv_event_t *e);

lv_obj_t *ui_led0Switch;
lv_obj_t *ui_led1panel;
lv_obj_t *ui_led1OffSymbol;
lv_obj_t *ui_led1ONSymbol;
lv_obj_t *ui_KitchenRoomlabel;
lv_obj_t *ui_led1OnLabel;
lv_obj_t *ui_led1OffLabel;
void ui_event_led1Switch(lv_event_t *e);

lv_obj_t *ui_led1Switch;
lv_obj_t *ui_Panel7;
lv_obj_t *ui_buttonLabel;
lv_obj_t *ui_buttonOffSymbol;
lv_obj_t *ui_buttonOnSymbol;
lv_obj_t *ui_mainLabel;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_gear[1] = { &ui_img_gear1_png };

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_led0Switch(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    led0_switch(e);
  }
}

void ui_event_led1Switch(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    led1_switch(e);
  }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
  lv_disp_t *dispp = lv_disp_get_default();
  lv_theme_t *theme =
    lv_theme_default_init(dispp,
                          lv_palette_main(LV_PALETTE_BLUE),
                          lv_palette_main(LV_PALETTE_RED),
                          true,
                          LV_FONT_DEFAULT);
  lv_disp_set_theme(dispp, theme);
  ui_main_screen_init();
  ui____initial_actions0 = lv_obj_create(NULL);
  lv_disp_load_scr(ui_main);
}
