// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: demo_hxd8357d

#ifndef _DEMO_HXD8357D_UI_H
#define _DEMO_HXD8357D_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_main
void ui_main_screen_init(void);

extern lv_obj_t *ui_main;
extern lv_obj_t *ui_Image19;
extern lv_obj_t *ui_led0panel;
extern lv_obj_t *ui_led0OffSymbol;
extern lv_obj_t *ui_led0ONSymbol;
extern lv_obj_t *ui_livingRoomlabel;
extern lv_obj_t *ui_led0OnLabel;
extern lv_obj_t *ui_led0OffLabel;
void ui_event_led0Switch(lv_event_t *e);

extern lv_obj_t *ui_led0Switch;
extern lv_obj_t *ui_led1panel;
extern lv_obj_t *ui_led1OffSymbol;
extern lv_obj_t *ui_led1ONSymbol;
extern lv_obj_t *ui_KitchenRoomlabel;
extern lv_obj_t *ui_led1OnLabel;
extern lv_obj_t *ui_led1OffLabel;
void ui_event_led1Switch(lv_event_t *e);

extern lv_obj_t *ui_led1Switch;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_buttonLabel;
extern lv_obj_t *ui_buttonOffSymbol;
extern lv_obj_t *ui_buttonOnSymbol;
extern lv_obj_t *ui_mainLabel;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE(ui_img_842152610);    // assets\silicon-labs-logo.png
LV_IMG_DECLARE(ui_img_buld_off_png);    // assets\buld_off.png
LV_IMG_DECLARE(ui_img_buld_on_png);    // assets\buld_on.png
LV_IMG_DECLARE(ui_img_button1_off_png);    // assets\button1_off.png
LV_IMG_DECLARE(ui_img_button1_on_png);    // assets\button1_on.png
LV_IMG_DECLARE(ui_img_gear1_png);    // assets\gear1.png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
