// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: demo_hxd8357d

#include "ui.h"
#include "sl_simple_led_instances.h"

void led0_switch(lv_event_t *e)
{
  (void) e;
  // Your code here
  sl_led_toggle(&sl_led_led0);
  if (sl_led_get_state(&sl_led_led0)) {
    lv_obj_add_flag(ui_led0OffSymbol, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_led0OffLabel, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_led0ONSymbol, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_led0OnLabel, LV_OBJ_FLAG_HIDDEN);
  } else {
    lv_obj_add_flag(ui_led0ONSymbol, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_led0OnLabel, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_led0OffSymbol, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_led0OffLabel, LV_OBJ_FLAG_HIDDEN);
  }
}

void led1_switch(lv_event_t *e)
{
  (void) e;
  // Your code here
  sl_led_toggle(&sl_led_led1);
  if (sl_led_get_state(&sl_led_led1)) {
    lv_obj_add_flag(ui_led1OffSymbol, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_led1OffLabel, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_led1ONSymbol, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_led1OnLabel, LV_OBJ_FLAG_HIDDEN);
  } else {
    lv_obj_add_flag(ui_led1ONSymbol, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_led1OnLabel, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_led1OffSymbol, LV_OBJ_FLAG_HIDDEN);
    lv_obj_clear_flag(ui_led1OffLabel, LV_OBJ_FLAG_HIDDEN);
  }
}
