// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_loader
void ui_loader_screen_init(void);

lv_obj_t *ui_loader;
lv_obj_t *ui_logo;
lv_obj_t *ui_Spinner1;

// SCREEN: ui_main
void ui_main_screen_init(void);

lv_obj_t *ui_main;
lv_obj_t *ui_Image4;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Label1;
void ui_event_BTN0(lv_event_t *e);

lv_obj_t *ui_BTN0;
lv_obj_t *ui_Led0Label;
lv_obj_t *ui_ControlTitle;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_BTN0(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  (void)target;

  if (event_code == LV_EVENT_PRESSED) {
    btn0_pressed_event_cb(e);
  }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
  lv_disp_t *dispp = lv_disp_get_default();
  lv_theme_t *theme =
    lv_theme_default_init(dispp,
                          lv_palette_main(LV_PALETTE_BLUE),
                          lv_palette_main(LV_PALETTE_RED),
                          false,
                          LV_FONT_DEFAULT);
  lv_disp_set_theme(dispp, theme);
  ui_loader_screen_init();
  ui_main_screen_init();
  ui____initial_actions0 = lv_obj_create(NULL);
  lv_disp_load_scr(ui_loader);
}
