// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "sl_simple_led_instances.h"

#define ON   1
#define OFF  0

static volatile bool led0_status = OFF;

void btn0_pressed_event_cb(lv_event_t *e)
{
  (void)e;
  if (led0_status == ON) {
    sl_led_turn_off(SL_SIMPLE_LED_INSTANCE(0));
    led0_status = OFF;
  } else {
    sl_led_turn_on(SL_SIMPLE_LED_INSTANCE(0));
    led0_status = ON;
  }
}
