// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_screenmain_screen_init(void)
{
  ui_screenmain = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_screenmain, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_bg_color(ui_screenmain,
                            lv_color_hex(0x000000),
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_screenmain, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelTextDemo = lv_label_create(ui_screenmain);
  lv_obj_set_width(ui_labelTextDemo, LV_SIZE_CONTENT); /// 1
  lv_obj_set_height(ui_labelTextDemo, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_labelTextDemo, 41);
  lv_obj_set_y(ui_labelTextDemo, -42);
  lv_obj_set_align(ui_labelTextDemo, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelTextDemo,
                    "Adafruit 1.14\" TFT LCD\nwith LVGL Demo\n");
  lv_obj_set_style_text_color(ui_labelTextDemo,
                              lv_color_hex(0x05FF00),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelTextDemo,
                            255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_labelTextDemo,
                             &lv_font_montserrat_14,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_imgSilabsLogo = lv_img_create(ui_screenmain);
  lv_img_set_src(ui_imgSilabsLogo, &ui_img_1802009198);
  lv_obj_set_width(ui_imgSilabsLogo, LV_SIZE_CONTENT); /// 75
  lv_obj_set_height(ui_imgSilabsLogo, LV_SIZE_CONTENT);  /// 43
  lv_obj_set_x(ui_imgSilabsLogo, 4);
  lv_obj_set_y(ui_imgSilabsLogo, 3);
  lv_obj_add_flag(ui_imgSilabsLogo, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_imgSilabsLogo, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_panelmain = lv_obj_create(ui_screenmain);
  lv_obj_set_width(ui_panelmain, 232);
  lv_obj_set_height(ui_panelmain, 79);
  lv_obj_set_x(ui_panelmain, 0);
  lv_obj_set_y(ui_panelmain, 25);
  lv_obj_set_align(ui_panelmain, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_panelmain, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_labelcontrolled = lv_label_create(ui_panelmain);
  lv_obj_set_width(ui_labelcontrolled, LV_SIZE_CONTENT); /// 1
  lv_obj_set_height(ui_labelcontrolled, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_labelcontrolled, 0);
  lv_obj_set_y(ui_labelcontrolled, -27);
  lv_obj_set_align(ui_labelcontrolled, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelcontrolled, "Control LEDs");
  lv_obj_set_style_text_color(ui_labelcontrolled,
                              lv_color_hex(0xFF0000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelcontrolled,
                            255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelled0 = lv_label_create(ui_panelmain);
  lv_obj_set_width(ui_labelled0, LV_SIZE_CONTENT); /// 1
  lv_obj_set_height(ui_labelled0, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_labelled0, -28);
  lv_obj_set_y(ui_labelled0, 27);
  lv_obj_set_align(ui_labelled0, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelled0, "LED 0");
  lv_obj_set_style_text_color(ui_labelled0,
                              lv_color_hex(0x002EFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelled0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_labelled1 = lv_label_create(ui_panelmain);
  lv_obj_set_width(ui_labelled1, LV_SIZE_CONTENT); /// 1
  lv_obj_set_height(ui_labelled1, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_x(ui_labelled1, 28);
  lv_obj_set_y(ui_labelled1, 27);
  lv_obj_set_align(ui_labelled1, LV_ALIGN_CENTER);
  lv_label_set_text(ui_labelled1, "LED 1");
  lv_obj_set_style_text_color(ui_labelled1,
                              lv_color_hex(0x002EFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_labelled1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_panelled0 = lv_obj_create(ui_screenmain);
  lv_obj_set_width(ui_panelled0, 63);
  lv_obj_set_height(ui_panelled0, 75);
  lv_obj_set_x(ui_panelled0, -83);
  lv_obj_set_y(ui_panelled0, 25);
  lv_obj_set_align(ui_panelled0, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_panelled0, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_imgled0off = lv_img_create(ui_panelled0);
  lv_img_set_src(ui_imgled0off, &ui_img_1258194689);
  lv_obj_set_width(ui_imgled0off, LV_SIZE_CONTENT); /// 64
  lv_obj_set_height(ui_imgled0off, LV_SIZE_CONTENT);  /// 64
  lv_obj_set_align(ui_imgled0off, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_imgled0off, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_imgled0off, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_imgled0on = lv_img_create(ui_panelled0);
  lv_img_set_src(ui_imgled0on, &ui_img_1258193662);
  lv_obj_set_width(ui_imgled0on, LV_SIZE_CONTENT); /// 64
  lv_obj_set_height(ui_imgled0on, LV_SIZE_CONTENT);  /// 64
  lv_obj_set_align(ui_imgled0on, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_imgled0on, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);

  lv_obj_clear_flag(ui_imgled0on, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_panelled1 = lv_obj_create(ui_screenmain);
  lv_obj_set_width(ui_panelled1, 63);
  lv_obj_set_height(ui_panelled1, 75);
  lv_obj_set_x(ui_panelled1, 83);
  lv_obj_set_y(ui_panelled1, 25);
  lv_obj_set_align(ui_panelled1, LV_ALIGN_CENTER);
  lv_obj_clear_flag(ui_panelled1, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_imgled1off = lv_img_create(ui_panelled1);
  lv_img_set_src(ui_imgled1off, &ui_img_1258194689);
  lv_obj_set_width(ui_imgled1off, LV_SIZE_CONTENT); /// 64
  lv_obj_set_height(ui_imgled1off, LV_SIZE_CONTENT);  /// 64
  lv_obj_set_align(ui_imgled1off, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_imgled1off, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_clear_flag(ui_imgled1off, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  ui_imgled1on = lv_img_create(ui_panelled1);
  lv_img_set_src(ui_imgled1on, &ui_img_1258193662);
  lv_obj_set_width(ui_imgled1on, LV_SIZE_CONTENT); /// 64
  lv_obj_set_height(ui_imgled1on, LV_SIZE_CONTENT);  /// 64
  lv_obj_set_align(ui_imgled1on, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_imgled1on, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);

  lv_obj_clear_flag(ui_imgled1on, LV_OBJ_FLAG_SCROLLABLE);    /// Flags

  lv_obj_add_event_cb(ui_panelled0, ui_event_panelled0, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_panelled1, ui_event_panelled1, LV_EVENT_ALL, NULL);
}
