// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_screenmain
void ui_screenmain_screen_init(void);

lv_obj_t *ui_screenmain;
lv_obj_t *ui_labelTextDemo;
lv_obj_t *ui_imgSilabsLogo;
lv_obj_t *ui_panelmain;
lv_obj_t *ui_labelcontrolled;
lv_obj_t *ui_labelled0;
lv_obj_t *ui_labelled1;
void ui_event_panelled0(lv_event_t *e);

lv_obj_t *ui_panelled0;
lv_obj_t *ui_imgled0off;
lv_obj_t *ui_imgled0on;
void ui_event_panelled1(lv_event_t *e);

lv_obj_t *ui_panelled1;
lv_obj_t *ui_imgled1off;
lv_obj_t *ui_imgled1on;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP != 0
#error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_panelled0(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    panel_led0_clicked_callback(e);
  }
}

void ui_event_panelled1(lv_event_t *e)
{
  lv_event_code_t event_code = lv_event_get_code(e);
  lv_obj_t *target = lv_event_get_target(e);
  if (event_code == LV_EVENT_CLICKED) {
    panel_led1_clicked_callback(e);
  }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
  lv_disp_t *dispp = lv_disp_get_default();
  lv_theme_t *theme =
    lv_theme_default_init(dispp,
                          lv_palette_main(LV_PALETTE_BLUE),
                          lv_palette_main(LV_PALETTE_RED),
                          false,
                          LV_FONT_DEFAULT);
  lv_disp_set_theme(dispp, theme);
  ui_screenmain_screen_init();
  ui____initial_actions0 = lv_obj_create(NULL);
  lv_disp_load_scr(ui_screenmain);
}
