// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_screenmain
void ui_screenmain_screen_init(void);

extern lv_obj_t *ui_screenmain;
extern lv_obj_t *ui_labelTextDemo;
extern lv_obj_t *ui_imgSilabsLogo;
extern lv_obj_t *ui_panelmain;
extern lv_obj_t *ui_labelcontrolled;
extern lv_obj_t *ui_labelled0;
extern lv_obj_t *ui_labelled1;
void ui_event_panelled0(lv_event_t *e);

extern lv_obj_t *ui_panelled0;
extern lv_obj_t *ui_imgled0off;
extern lv_obj_t *ui_imgled0on;
void ui_event_panelled1(lv_event_t *e);

extern lv_obj_t *ui_panelled1;
extern lv_obj_t *ui_imgled1off;
extern lv_obj_t *ui_imgled1on;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1802009198);    // assets\silabs-logo.png
LV_IMG_DECLARE(ui_img_1258194689);    // assets\led (1).png
LV_IMG_DECLARE(ui_img_1258193662);    // assets\led (2).png

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
