// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void panel_led0_clicked_callback(lv_event_t *e)
{
  // Your code here
}

void panel_led1_clicked_callback(lv_event_t *e)
{
  // Your code here
}
