// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "sl_simple_led_instances.h"
#include "sl_simple_button_instances.h"

#define ON                  1
#define OFF                 0

#ifndef BUTTON_INSTANCE_0
#define BUTTON_INSTANCE_0   sl_button_btn0
#endif

#ifndef BUTTON_INSTANCE_1
#define BUTTON_INSTANCE_1   sl_button_btn1
#endif

static volatile bool led0_status = OFF;
static volatile bool led1_status = OFF;

void btn0_pressed_event_cb(lv_event_t *e)
{
  (void)e;
  if (led0_status == ON) {
    sl_led_turn_off(SL_SIMPLE_LED_INSTANCE(0));
    led0_status = OFF;
  } else {
    sl_led_turn_on(SL_SIMPLE_LED_INSTANCE(0));
    led0_status = ON;
  }
}

void btn1_pressed_event_cb(lv_event_t *e)
{
  (void)e;
  if (led1_status == ON) {
    sl_led_turn_off(SL_SIMPLE_LED_INSTANCE(1));
    led1_status = OFF;
  } else {
    sl_led_turn_on(SL_SIMPLE_LED_INSTANCE(1));
    led1_status = ON;
  }
}

/***************************************************************************//**
 * Callback on button change.
 ******************************************************************************/
void sl_button_on_change(const sl_button_t *handle)
{
  if (sl_button_get_state(handle) == SL_SIMPLE_BUTTON_PRESSED) {
    if (&BUTTON_INSTANCE_0 == handle) {
      if (lv_obj_has_state(ui_BTN0, LV_STATE_CHECKED)) {
        lv_obj_clear_state(ui_BTN0, LV_STATE_CHECKED);
        sl_led_turn_off(SL_SIMPLE_LED_INSTANCE(0));
        led0_status = OFF;
      } else {
        lv_obj_add_state(ui_BTN0, LV_STATE_CHECKED);
        sl_led_turn_on(SL_SIMPLE_LED_INSTANCE(0));
        led0_status = ON;
      }
    } else if (&BUTTON_INSTANCE_1 == handle) {
      if (lv_obj_has_state(ui_BTN1, LV_STATE_CHECKED)) {
        lv_obj_clear_state(ui_BTN1, LV_STATE_CHECKED);
        sl_led_turn_off(SL_SIMPLE_LED_INSTANCE(1));
        led1_status = OFF;
      } else {
        lv_obj_add_state(ui_BTN1, LV_STATE_CHECKED);
        sl_led_turn_on(SL_SIMPLE_LED_INSTANCE(1));
        led1_status = ON;
      }
    }
  }
}
